[theme]
primaryColor = "#FF6B35"
backgroundColor = "#ffecd2"
secondaryBackgroundColor = "#ffffff"
textColor = "#1A1A2E"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
